/* tslint:disable */

/**
 * AUTO-GENERATED FILE @ 2018-07-06 16:46:40 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/graphql-ts-server-boilerplate -t teams -t knex_migrations -t users -t granted_permissions -t knex_migrations_lock -t permissions -s public
 *
 */

export namespace teamsFields {
    export type id = string;
    export type name = string;

}

export interface teams {
    id: teamsFields.id;
    name: teamsFields.name;

}

export namespace knex_migrationsFields {
    export type id = number;
    export type name = string | null;
    export type batch = number | null;
    export type migration_time = Date | null;

}

export interface knex_migrations {
    id: knex_migrationsFields.id;
    name: knex_migrationsFields.name;
    batch: knex_migrationsFields.batch;
    migration_time: knex_migrationsFields.migration_time;

}

export namespace usersFields {
    export type id = string;
    export type createdAt = Date | null;
    export type updatedAt = Date | null;
    export type deletedAt = Date | null;
    export type email = string;
    export type password = string;

}

export interface users {
    id: usersFields.id;
    createdAt: usersFields.createdAt;
    updatedAt: usersFields.updatedAt;
    deletedAt: usersFields.deletedAt;
    email: usersFields.email;
    password: usersFields.password;

}

export namespace granted_permissionsFields {
    export type id = number;
    export type name = string;
    export type teamId = string;
    export type permissionId = number;
    export type userId = string;

}

export interface granted_permissions {
    id: granted_permissionsFields.id;
    name: granted_permissionsFields.name;
    teamId: granted_permissionsFields.teamId;
    permissionId: granted_permissionsFields.permissionId;
    userId: granted_permissionsFields.userId;

}

export namespace knex_migrations_lockFields {
    export type index = number;
    export type is_locked = number | null;

}

export interface knex_migrations_lock {
    index: knex_migrations_lockFields.index;
    is_locked: knex_migrations_lockFields.is_locked;

}

export namespace permissionsFields {
    export type id = number;
    export type name = string;

}

export interface permissions {
    id: permissionsFields.id;
    name: permissionsFields.name;

}
